### ISSUE TITLE
Ui jumps to top when grid in details component is sorted

### ISSUE THREAD

**Issue by idil-k** [vaadin/vaadin-details-flow#44]
I have a view with multiple details component. In each detail component, there is a grid with sortable columns. How to reproduce:

1. Expand a detail component
2. Scroll down so that the detail summary is not visible in the page any more
3. Sort a column twice
4. In the second sort the UI jumps.

- After the first sort, I observe the same behaviour in all columns of that details component
- One detail is, if the title is visible in the view, this does not happen.
- The same behaviour is also observed in the accordions component. 

Here is an implementation to reproduce the bug from [Johannes](https://gist.github.com/johannest/4c2c22dfc7dfcfed1dee42623e8adeb0)  

Would be great if this was fixed!

**Comment by javier-godoy** [comment]
Reproduced with Vaadin 14.1.27 using Chrome (81.0.4044.129).

**Comment by tomivirkki** [comment]
Not the most elegant workaround (as it might affect focusing the Details component with tab key):
```java
details.getElement().executeJs("this._focus = function(){}");
```
